# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogory',
            new_name='Category',
        ),
    ]
