# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200322_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'todoes'},
        ),
    ]
