# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20200322_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
