# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20200322_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todo_app.Category'),
            preserve_default=False,
        ),
    ]
