# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
    ]
